/* SPDX-License-Identifier: Apache-2.0 */
#ifndef __BK7258_BL2_SYSFLASH_H
#define __BK7258_BL2_SYSFLASH_H

#define CP_PRIMARY_ID 0
#define CP_SECONDARY_ID 1
#define AP_PRIMARY_ID 2
#define AP_SECONDARY_ID 3
#define SCRATCH_ID 4
#define FLASH_AREA_IMAGE_PRIMARY(x) ((x) == 0 ? CP_PRIMARY_ID : AP_PRIMARY_ID)
#define FLASH_AREA_IMAGE_SECONDARY(x) ((x) == 0 ? CP_SECONDARY_ID : AP_SECONDARY_ID)
#define FLASH_AREA_IMAGE_SCRATCH SCRATCH_ID

#endif
