BK7258_BOARD_SCHEMA=1
BK7258_BOARD_NAME=aidk_ai_toy
BK7258_BOARD_CP_CONFIG=boards/bk7258/aidk_ai_toy/configs/team441_cp
BK7258_BOARD_AP_CONFIG=boards/bk7258/aidk_ai_toy/configs/team441_ap
BK7258_BOARD_PARTITION=boards/bk7258/aidk_ai_toy/bk7258_ab_fixed_block_full_release.csv
BK7258_BOARD_RELEASE_POLICY=boards/bk7258/common/release/bk7258_product.release.csv
