abufsrc@Music0=outputs=1:map=1:wait_release=1,asubgraph@SpeakerRate=inputs=1:outputs=1:map=1,adevsink@pcm0p=wait_release=1:format=nuttx:devname=/dev/audio/pcm0p:sample_fmt=s16:sample_rate=16000:ch_layout=mono;
adevsrc@pcm0c=format=nuttx:devname=/dev/audio/pcm0c:sample_fmt=s16:sample_rate=16000:ch_layout=mono:map=1,abufsink@Capture0=inputs=1
<subgraph>SpeakerRate:aresample=16000:osf=s16:ochl=mono
