/* Generated by G:/CIE/R1/tools/generate-vendor-eye-assets.py. */
#ifndef __BOARDS_BK7258_AIDK_AI_TOY_SRC_BK7258_AIDK_EYE_ASSETS_H
#define __BOARDS_BK7258_AIDK_AI_TOY_SRC_BK7258_AIDK_EYE_ASSETS_H

#include <stdint.h>

#define BK7258_AIDK_EYE_ASSET_WIDTH  320u
#define BK7258_AIDK_EYE_ASSET_HEIGHT 160u

struct bk7258_aidk_eye_packed_asset_s
{
  const uint16_t *palette;
  const char *encoded_pixels;
  uint32_t encoded_size;
};

extern const struct bk7258_aidk_eye_packed_asset_s
  g_bk7258_aidk_eye_closed_packed;
extern const struct bk7258_aidk_eye_packed_asset_s
  g_bk7258_aidk_eye_half_packed;
extern const struct bk7258_aidk_eye_packed_asset_s
  g_bk7258_aidk_eye_open_packed;

#endif
